version: '3'

services:
  php-fpm:
    build:
      context: .
      target: php-fpm
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:1.20
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  # npm:
  #   build:
  #     context: .
  #     target: npm
  #   working_dir: /assets
  #   volumes:
  #     - ./:/assets
  #   command: npm run watch

  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    ports:
      - 33060:3306
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
      - redisdata:/data

volumes:
  mysqldata: null
  redisdata: null
